#!/bin/sh

case "$1" in
  start)
    echo "=========================================="
    echo "         Starting armiumOS v1.0           "
    echo "=========================================="

    mount -t proc proc /proc
    mount -t sysfs sysfs /sys

    ip link set dev eth0 up
    udhcpc -i eth0

    echo "[armiumOS] Starting Security Engine..."
    python3 /root/armiumos_av_guard.py &

    echo "[armiumOS] Initializing Display Compositor..."
    weston --config=/etc/xdg/weston/weston.ini &
    sleep 2

    echo "[armiumOS] Desktop interface loaded with Chrome, Steam & Settings."
    ;;
  stop)
    killall chromium-browser
    killall steam
    killall lxqt-config
    killall weston
    killall python3
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac
